const fakeProducts = [
  {
    name: "Farm Fresh Tomatoes",
    price: 40,
    category: "Vegetables",
    description: "Organic vine-ripened tomatoes directly from the local farm in Rahon.",
    image: "https://images.unsplash.com/photo-1582284540020-8acbe03f4924?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dG9tYXRvfGVufDB8fDB8fHww",
    vendorName: "Farmer Sharma",
    inStock: true,
    quantity:"kg",
  },
  {
    name: "Spicy Vada Pav",
    price: 20,
    category: "Street Food",
    description: "Classic Mumbai-style Vada Pav with spicy garlic chutney.",
    image: "https://images.unsplash.com/photo-1750767397012-3413ba4fdbc7?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHZhZGElMjBwYXZ8ZW58MHx8MHx8fDA%3D",
    vendorName: "Gupta Snacks",
    inStock: true,
    quantity:"psc",
  },
  {
    name: "Golden Alphonso Mangoes",
    price: 120,
    category: "Fruits",
    description: "Sweet and juicy seasonal mangoes. Sold by the dozen.",
    image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWFuZ29lc3xlbnwwfHwwfHx8MA%3D%3D",
    vendorName: "Azad Fruits",
    inStock: true,
    quantity:"kg",
  },
  {
    name: "Crispy Pani Puri",
    price: 30,
    category: "Street Food",
    description: "Set of 6 crispy puris with tangy mint water and potato filling.",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500",
    vendorName: "Chauhan Chaat",
    inStock: true,
    quantity:"pac",
  },
  {
    name: "Organic Green Spinach",
    price: 25,
    category: "Vegetables",
    description: "Freshly harvested leafy greens, rich in iron and nutrients.",
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500",
    vendorName: "Green Valley Farm",
    inStock: true,
    quantity:"kg",
  },
  {
    name: "Masala Chai",
    price: 15,
    category: "Other",
    description: "Strong ginger and cardamom tea brewed fresh on the stall.",
    image: "https://media.istockphoto.com/id/1482828620/photo/clay-tea-cup-being-hold-in-the-hand.webp?a=1&b=1&s=612x612&w=0&k=20&c=4o04J51HDfPkNtOeLnHoWZz4VI7QtKj6QlaY24c40xs=",
    vendorName: "Pappu Tea Stall",
    inStock: true,
    quantity:"psc",
  },
  {
    name: "Basmati Rice (Bulk)",
    price: 85,
    category: "Grains",
    description: "Long-grain aromatic basmati rice directly from the mill.",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500",
    vendorName: "Punjab Grain Store",
    inStock: true,
    quantity:"kg",
    
  },
  {
    name: "Red Carrots",
    price: 35,
    category: "Vegetables",
    description: "Sweet winter carrots, perfect for Gajar ka Halwa.",
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=500",
    vendorName: "Farmer Sital",
    inStock: true,
    quantity:"kg",
    
  },
  {
    name: "Butter Pav Bhaji",
    price: 80,
    category: "Street Food",
    description: "Mashed vegetable curry served with two buttered buns.",
    image: "https://images.unsplash.com/photo-1769030905851-c0e0a4fe5c51?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHZhZGElMjBwYXZ8ZW58MHx8MHx8fDA%3D",
    vendorName: "Metro Pav Bhaji",
    inStock: true,
    quantity:"psc",
    
  },
  {
    name: "Sweet Corn Cobs",
    price: 25,
    category: "Vegetables",
    description: "Roasted or boiled corn with lemon and black salt.",
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=500",
    vendorName: "Desi Corn Hub",
    inStock: true,
    quantity:"psc",
    
  }
];

export default { data: fakeProducts};